services:
  rabbitmq:
    image: rabbitmq:management
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit_net
    command: rabbitmq-server
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10

  service:
    container_name: ${APP_CONTAINER_NAME:-app}
    build:
      dockerfile: Dockerfile
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - rabbit_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

networks:
  rabbit_net:
